### PR TITLE
Update gstreamer-rs dep

### PR DESCRIPTION
**Pull request by gdesmott**
Here is a port to the latest gstreamer-rs release.

### CODE REVIEW

**Comment by nagisa** [comment]
Thanks! I was meaning to do this myself this weekend, so your timing is impeccable!

It seems like you will need to bump the MSRV to [1.63](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/blob/0.19/gstreamer/Cargo.toml#L14). If you could also add a similar `rust-version` annotation to `Cargo.toml` while at it, it would be great.

**Comment by gdesmott** [comment]
Sure, here you go.

**Review by sdroege — APPROVED** [review]

**Comment by gdesmott** [comment]
Thanks for the quick review!

Any chance you could publish a release? :)

**Comment by nagisa** [comment]
Published. Was waiting for the CI to go through.

**Pull request merged**
